version: '3'

services:
  mariadb:
    image: mariadb:10.3
    restart: always
    ports:
      - 13280:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: chat_db
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
      - mariadb
